1--------------------
SELECT HLOTUN, SUKUNIMI, ETUNIMI, PALKKA, KAUPUNKI
FROM HENKILO
WHERE KAUPUNKI = ('TURKU')
UNION
SELECT
  '171190-122A' AS HLOTUN, 'Aaltonen' AS SUKUNIMI, 'Anneli' ETUNIMI, 3000 AS PALKKA, 'TURKU' AS KAUPUNKI
UNION
SELECT
  '171190-123B' AS HLOTUN, 'Aaltonen' AS SUKUNIMI, 'Antti' ETUNIMI, 3000 AS PALKKA, 'TURKU' AS KAUPUNKI
UNION
SELECT
  '160199-4235' AS HLOTUN, 'Penttila' AS SUKUNIMI, 'Saara' ETUNIMI, 2300 AS PALKKA, 'TAMPERE' AS KAUPUNKI
ORDER BY SUKUNIMI

2--------------------
SELECT A.HLOTUN,
       C.TUOTEKDI,
       COUNT(DISTINCT A.HLOTUN) AS NUM
FROM ((HENKILO A
       JOIN TILOTS B ON A.HLOTUN = B.HLOTUN)
      JOIN TILRIV C ON B.TILNRO = C.TILNRO)
WHERE C.TUOTEKDI = '1007'
  OR C.TUOTEKDI = '1031'
  OR C.TUOTEKDI = '1019'
  OR C.TUOTEKDI = '1022'
  OR C.TUOTEKDI = '1027'
GROUP BY A.HLOTUN,
         C.TUOTEKDI

3--------------------
SELECT MAX(YEAR(TILAUSPV)) AS VUOSI,
       MAX(MONTH(TILAUSPV)) AS KUUKAUSI,
       SUM(CASE
               WHEN DAY(TILAUSPV) <= 20 THEN 1
               ELSE 0
           END) AS 'D1-20',
       SUM(CASE
               WHEN DAY(TILAUSPV) = 21
                    OR DAY(TILAUSPV) = 22 THEN 1
               ELSE 0
           END) AS 'D21-22',
       SUM(CASE
               WHEN DAY(TILAUSPV) = 23
                    OR DAY(TILAUSPV) = 24 THEN 1
               ELSE 0
           END) AS 'D23-24',
       SUM(CASE
               WHEN DAY(TILAUSPV) >= 25 THEN 1
               ELSE 0
           END) AS 'D25-LOPPU'
FROM TILOTS

4--------------------
SELECT A.TILAUSPV,
       B.KAUPUNKI,
       SUM(C.MAARA * D.YKSHINTA) AS ARVO
FROM TILOTS A
JOIN HENKILO B ON A.HLOTUN = B.HLOTUN
JOIN TILRIV C ON C.TILNRO = A.TILNRO
JOIN VARASTO D ON D.TUOTEKDI = C.TUOTEKDI
GROUP BY A.TILAUSPV,
         B.KAUPUNKI
