1--------------------
SELECT SUKUNIMI,
       CASE
           WHEN PALKKA BETWEEN 0 AND 4999 THEN '0-4999'
           WHEN PALKKA BETWEEN 5000 AND 5999 THEN '5000-5999'
           WHEN PALKKA BETWEEN 6000 AND 9999 THEN '6000-9999'
       END AS Luokka
FROM HENKILO
ORDER BY Luokka

2--------------------
SELECT TOP 1 C.POSTITP,
           SUM(B.MAARA*D.YKSHINTA) AS ARVO
FROM TILOTS A
JOIN TILRIV B ON A.TILNRO = B.TILNRO
JOIN ASIAKAS C ON A.ASNRO = C.ASNRO
JOIN VARASTO D ON B.TUOTEKDI = D.TUOTEKDI
GROUP BY C.POSTITP
ORDER BY ARVO DESC

3--------------------
SELECT POSTITP,
       [HELSINKI] AS HELSINKI,
       [TAMPERE] AS TAMPERE,
       [TURKU] AS TURKU
FROM
  ( SELECT A.POSTITP,
           T.ASNRO,
           H.KAUPUNKI
   FROM TILOTS T
   JOIN HENKILO H ON H.HLOTUN = T.HLOTUN
   JOIN ASIAKAS A ON A.ASNRO = T.ASNRO ) AS DATA PIVOT ( COUNT(ASNRO)
                                                        FOR KAUPUNKI IN ([HELSINKI], [TAMPERE], [TURKU]) )AS PIVOT_TAULU
ORDER BY PIVOT_TAULU.POSTITP
SELECT TILNRO,
       TILAUSPV
FROM TILOTS
WHERE TILNRO IN
    (SELECT TILNRO
     FROM TILRIV
     WHERE TUOTEKDI = 1005
       OR TUOTEKDI = 1021
     GROUP BY TILNRO
     HAVING COUNT(TUOTEKDI) > 1 )

4------------------
 SELECT TILNRO, TILAUSPV FROM TILOTS WHERE TILNRO IN
     (SELECT TILNRO FROM TILRIV
          WHERE TUOTEKDI = 1005 OR TUOTEKDI = 1021
          GROUP BY TILNRO
          HAVING COUNT(TUOTEKDI) > 1
 )

5--------------------
WITH T1 (EsimiesID, HenkiloID, Nimi, Taso) AS
  (SELECT ESIMIES,
          HLOTUN,
          ETUNIMI +' '+ SUKUNIMI,
          CASE
              WHEN (ESIMIES) IS NULL THEN 0
              ELSE 1
          END
   FROM HENKILO)
SELECT EsimiesID,
       HenkiloID,
       Nimi,
       Taso
FROM T1
ORDER BY ESIMIESID
